DROP GIT REPOSITORY COMPUTE_WH_DB.PUBLIC.BUGTRACKER_REPO;

CREATE GIT REPOSITORY COMPUTE_WH_DB.PUBLIC.HOLO_REPO
  API_INTEGRATION = BUGTRACKER
  GIT_CREDENTIALS = COMPUTE_WH_DB.PUBLIC.GITHUB_SECRET
  ORIGIN = 'https://github.com/elitecranker/Holo-Projector.git';